### ISSUE TITLE
Add option multi-select

### ISSUE THREAD

**Issue by fakhamatia** [L3v3L/vs-focus#6]
Please add an option for multi-select.

![Peek 2020-02-27 00-04](https://user-images.githubusercontent.com/20030910/75385548-335a2900-58f5-11ea-894c-f798f982a856.gif)

**Comment by L3v3L** [comment]
sounds like a great ideia, I'll look into it ;)

**Comment by L3v3L** [comment]
feature should now be live in 0.0.6 version ;)
